global:
  scrape_interval: 15s # How often to scrape targets by default

scrape_configs:
  - job_name: 'Prometheus'
    static_configs:
      - targets: ['prometheus:9090'] # Target to scrape Prometheus itself
  - job_name: 'NestJS App'
    static_configs:
      - targets:
          - nestjsapp:3000
